In [2]:
# 난수(random number)를 발생시키는 방법
# 기준이 되는 시작 숫자를 시드(seed)라고 함

import numpy as np
np.random.seed(0)

In [3]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [4]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [5]:
# 순서 바꾸기
# shuffle 함수
# 자체 변환(in-place) 함수로 한 번 사용하면 변수의 값이 바뀜

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.random.shuffle(x)
x

array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

In [9]:
# 데이터 샘플링

np.random.choice(5, 5, replace=False)   # shuffle 명령과 같다.

array([1, 4, 2, 3, 0])

In [10]:
np.random.choice(5, 3, replace=False)   # 3개만 선택

array([0, 1, 4])

In [11]:
np.random.choice(5,10)   # 반복해서 10개 선택

array([4, 2, 0, 0, 4, 0, 4, 1, 4, 1])

In [13]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])   # 선택 확률을 다르게 해서 10개 선택

array([3, 3, 3, 0, 3, 3, 2, 2, 3, 3])

In [15]:
# rand: 0부터 1사이의 균일 분포
np.random.rand(3, 5)

array([[0.6235101 , 0.33800761, 0.67475232, 0.31720174, 0.77834548],
       [0.94957105, 0.66252687, 0.01357164, 0.6228461 , 0.67365963],
       [0.971945  , 0.87819347, 0.50962438, 0.05571469, 0.45115921]])

In [16]:
# randn: 표준 정규 분포
# 기댓값(mean)이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성
np.random.randn(3, 5)

array([[-0.04411241, -0.36326702, -0.01234481,  0.04212149,  1.95929589],
       [-0.1984257 ,  0.33053441, -1.43582841,  0.02752832,  1.12060466],
       [-0.22403878, -0.42018339,  0.99982969,  0.43103415, -0.65091287]])

In [17]:
# randint: 균일 분포의 정수 난수
# numpy.random.randint(low, high=None, size=None)
np.random.randint(10, 20, size=(3, 5))

array([[13, 18, 18, 18, 12],
       [13, 12, 10, 18, 18],
       [13, 18, 12, 18, 14]])

In [35]:
# 연습 문제
# 동전을 100번 던진 결과
# 앞면을 숫자 1, 뒷면을 숫자 0으로 가정
# 앞면이 나올 확률

np.random.seed(0)
res = np.random.randint(0, 2, 100)
res.sum() / len(res)    # np.mean(res)

0.56

In [36]:
# 정수 데이터 카운팅
# unique() 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
# return_counts 인수를 True로 설정하면 각 값의 데이터 개수도 출력

np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [37]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [38]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [39]:
count

array([2, 2, 1], dtype=int64)

In [47]:
# 특정 범위안의 수인 경우에는 bincount 함수에 minlength 인수를 설정
# bincount 함수는 0부터 minlength - 1까지의 숫자에 대해 각각 카운트
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)