In [1]:
import numpy as np

In [2]:
# 주사위를 100번 던져서 나오는 숫자의 평균

np.random.seed(0)
result = np.random.randint(1, 7, 100)
print(result)
np.mean(result)

[5 6 1 4 4 4 2 4 6 3 5 1 1 5 3 2 1 2 6 2 6 1 2 5 4 1 4 6 1 3 4 1 2 4 6 4 4
 1 2 2 2 1 3 5 4 4 3 5 3 1 1 5 6 6 1 5 2 5 2 3 3 1 2 2 2 2 4 4 3 4 1 4 6 5
 2 3 5 4 5 5 5 4 5 5 5 1 5 4 3 6 6 6 1 2 6 2 4 1 6 1]


3.42

In [3]:
# 두 넘파이 배열을 활용하여 아래의 계산 결과 구하기

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [4]:
# 1부터 9까지 정수 값을 갖는 1차원 ndarray를 활용하여 3부터 27까지의 3의 배수를 갖는 ndarray

a = np.arange(1, 10)
a*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
# zeros()와 인덱싱을 활용

a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
# np.arange(50)으로 만든 1차원 ndarray를 다음과 같이 출력

a = (np.arange(50))
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
# 빈 문자열을 갖는 shape이 (3, 3, 3) ndarray

np.zeros((3, 3, 3), dtype = 'U10')

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [8]:
# np.full()
# 하나의 특정 값으로 배열의 값을 채우고 싶을 때
# 첫번째 인자는 shape을 두번째 인자에는 요소로 채울 값을 전달
# numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)

In [9]:
np.full((3, 3, 3), '', dtype='U10')

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [10]:
# (3, 3, 3) shape의 ndarray를 생성

np.full((3, 3, 3), 'playdata')

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [11]:
# 1부터 40까지의 짝수를 갖는 (2, 2, 5) shape의 ndarray를 생성

(np.arange(2, 41, 2)).reshape(2, 2, 5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [12]:
# 단위 행렬
#  np.eye(n) 메서드

# 4 x 4 크기의 정수 타입의 단위 행렬
np.eye(4, dtype="i")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [13]:
# 데이터 타입 변경하기
# astype() 메서드
# 첫번째 위치 키워드 인수인 dtype은 값을 필수로 입력
# ndarray.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

np.random.seed(0)
a = np.random.randint(0, 2, size=9)
(a.astype('bool')).reshape(3, 3)

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [14]:
# rand() 메서드를 활용하여 0과 1 사이의 실수 10개를 갖는 1차원 ndarray를 생성
# 이 배열 요소에 각 10을 곱하고 데이터 타입을 int로 변경

np.random.seed(0)
a = np.random.rand(10)
b = a*10
b.astype('i')

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3], dtype=int32)

In [15]:
# np.ones((10, 10))를 만들고 아래와 같이 배열의 안쪽 값을 0으로 변경

a = np.ones((10, 10))
a[1:-1, 1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
# np.ones((10, 10))를 만들고 아래와 같이 배열의 바깥쪽 값을 0으로 변경

a = np.ones((10, 10))
a[:, [0, -1]] = 0
a[[0, -1], :] = 0
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
# 조건문 활용 풀이

a = np.ones((10, 10))
for i in range(10):
    if i == 0:
        a[i] = 0
        a[:,i] = 0
    elif i == 9:
        a[i] = 0
        a[:,i] = 0
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
# np.ones((8, 8))를 만들고 아래와 같이 체크문양의 값으로 변경

a = np.ones((8, 8), dtype='i')
a[1::2, 0::2] = 0
a[0::2, 1::2] = 0
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [19]:
# array([1, 0], [0, 1])를 만들고 아래와 같이 체크문양의 값으로 변경

a = np.array(([1, 0], [0, 1]))
np.tile(a, (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [20]:
# 또다른 풀이

np.tile(np.eye(2), (4, 4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [21]:
# boolean indexing
# 같은 shape과 len의 boolean type의 값을 갖는 ndarray로 인덱싱
# 해당 위치에 대해 True면 값을 취하고 False면 가져오지 않음

a = np.arange(1, 5)
print(a)

[1 2 3 4]


In [22]:
even = np.array([True if i%2==0 
                 else False 
                 for i in range(1, 5)])
print(even)

[False  True False  True]


In [23]:
# dtype('bool')의 ndarray를 인덱스로 활용
# 인덱스로 쓰인 ndarray의 값이 True인 곳의 값만 반환

a[even]

array([2, 4])

In [24]:
# 0부터 10까지의 정수를 갖는 1차원 ndarray를 만들기
# 그 중 3초과 7미만의 숫자는 음수로 변경

a = np.arange(11)

num = np.array([True if 3<i<7 else False for i in a])
a[num] = -a[num]
print(a)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [25]:
# 또다른 풀이

a = np.arange(11)
a[(3<a) & (7>a)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [26]:
# 1부터 100까지의 3의 배수를 갖는 1차원 ndarray를 생성하고 그 전체의 합

a = np.arange(1, 101)
num = np.array([True if i%3==0 else False for i in range(1, 101)])
sum(a[num])

1683

In [27]:
# linspace()를 활용하여 다음과 같은 1차원 ndarray 만들기

a = np.linspace(0.1, 0.9, 9)
a

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [28]:
# 로또 번호 1부터 45까지의 숫자 6개를 추출하는 프로그램
# 비복원추출: random.choice(a, size=None, replace=True, p=None)

while True:
    try: 
        number = int(input())
        if number>0:
            for _ in range(number):
                result = np.random.choice(range(1, 46), size=6, replace=False)
                result.sort()
                print(result)
            break
        else:
            print("자연수만 입력해주세요.")
    except ValueError:
        print("자연수만 입력해주세요.")
        continue

 3


[ 7 33 35 37 44 45]
[ 3 14 17 23 25 34]
[ 6  8 13 17 23 38]


In [29]:
# 또다른 풀이

while True:
    try: 
        count = int(input("로또 몇개 드릴까요?"))
        if count<0:
            raise Error
        numbers = np.arange(1, 46)
        lottos = [np.sort(np.random.choice(numbers, size=6, replace=False)) for _ in range(count)]
        display(lottos)
        break
    except:
        print("자연수만 입력해주세요.")

로또 몇개 드릴까요? 3


[array([ 2,  8, 11, 18, 24, 39]),
 array([10, 15, 18, 33, 34, 42]),
 array([ 7, 17, 20, 29, 31, 34])]

In [30]:
# 200ms를 넘기는 값의 개수가 총 몇개인지 구해보기

resp_time = np. array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
 199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
 177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
 168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
 55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
 49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
 186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
 199, 55, 151, 183, 152, 119, 193, 110, 204])

result = np.array([True if i>200 
                  else False
                  for i in resp_time])
len(resp_time[result])

8

In [31]:
# 또다른 풀이

(resp_time > 200).sum()

8

In [32]:
# 사분위수 구하기

resp_time = np. array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
 199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
 177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
 168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
 55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
 49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
 186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
 199, 55, 151, 183, 152, 119, 193, 110, 204])

res_1 = np.percentile(resp_time, 25)
res_2 = np.percentile(resp_time, 50)
res_3 = np.percentile(resp_time, 75)
res_4 = np.percentile(resp_time, 100)

print(f"1사분위 수: {res_1}",
      f"2사분위 수: {res_2}",
      f"3사분위 수: {res_3}",
      f"최댓값: {res_4}", sep='\n')

1사분위 수: 71.5
2사분위 수: 131.0
3사분위 수: 175.5
최댓값: 218.0


In [33]:
# 또다른 풀이 

for i, v in enumerate(range(25, 76, 25)):
    print(f"{i+1}분위({v}%) 값: {np.percentile(resp_time, v)}ms")

1분위(25%) 값: 71.5ms
2분위(50%) 값: 131.0ms
3분위(75%) 값: 175.5ms


In [60]:
# 뽀로로가 0번, 루피가 1번, 크롱이 2번일 때
# 누가 몇표로 학생 회장에 당선되었는지 확인

p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
 1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
 2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
 2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
 2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
 1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
 2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
 0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
 0, 1])

index, count = np.unique(result, return_counts=True)
winner = count.argmax()

print(f"{p[winner]}가 {np.max(count)}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.


In [64]:
# 또다른 풀이

count = np.bincount(result, minlength=3)
winner_index = count.argmax()
print(f"{p[winner_index]}가 {count[winner_index]}표로 반장으로 선출되었습니다.")

뽀로로가 81표로 반장으로 선출되었습니다.
